version: "3.3"  # optional since v1.27.0
services:
  nginx:
    image: nginx:latest
    expose:
      - '8001'
    ports:
      - 8001:8001
    volumes:
      - ./servers/nginx/conf.d/:/etc/nginx/conf.d/
      - ./servers/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./web:/var/www/sultstua/html
    restart: unless-stopped
    networks:
      - sultstua-external
    depends_on:
      - api
  api:
    build: ./api
    expose:
      - '5000'
    secrets:
      - mysql_user_password
      - flask.env
    env_file:
      - ./secrets/${SECRET_SOURCE}/flask.env
    volumes:
      - ./api/:/app
    restart: unless-stopped
    networks:
      - sultstua-internal
      - sultstua-external
    depends_on:
      - mysql
  mysql:
    build: ./servers/mysql
    expose:
      - '3306'
    secrets:
      - mysql_root_password
      - mysql_user_password
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_user_password
    env_file:
      - ./secrets/${SECRET_SOURCE}/mysql.env
    volumes:
      - mysql:/var/lib/mysql
      - ./api/db:/app/db
    networks:
      - sultstua-internal

volumes:
  mysql:
    driver: local

secrets:
  mysql_root_password:
    file: ./secrets/${SECRET_SOURCE}/mysql_root_password
  mysql_user_password:
    file: ./secrets/${SECRET_SOURCE}/mysql_user_password
  mysql.env:
    file: ./secrets/${SECRET_SOURCE}/mysql.env
  flask.env:
    file: ./secrets/${SECRET_SOURCE}/flask.env
    
networks:
  sultstua-internal:
  sultstua-external:
